### ISSUE TITLE
**Please add inline formula support**

### ISSUE THREAD

**Issue by zkyue** [zwbetz-gh/cayman-hugo-theme#2]
**Please add inline formula support**
I found that this theme will fail when confront inline formula

**Comment by zwbetz-gh** [comment]
I've dug into this, but am not sure why inline math works in the [hugo themes demo for cayman](https://themes.gohugo.io//theme/cayman-hugo-theme/math-typesetting/), but not in the theme when it's installed locally. 

If you have ideas on how to fix, please feel free to submit a PR. 

For reference, here's is the sample code from the [hugoBasicExample site](https://github.com/gohugoio/hugoBasicExample/blob/master/content/post/math-typesetting.mmark).

**Comment by zwbetz-gh** [comment]
Fixed in 8917303c3be2f003f35d584f38a6a9ebea5903f6.

**Comment by zkyue** [comment]
hahaha, thanks for your work! I have no idea about js, so ... but really thank you!
